function update(){
 const d=decision();lastDecision=d;const e=d.e,p=d.p,st=d.st,dq=d.dq,sim=d.sim,rt=reTotals(),sa=stressAssets(),fa=financialAssets(),safe=n('safe');
 $('faKpi').innerHTML=`${fmt(fa)}<span class="unit">万円</span>`;$('assetAsOfHint').textContent=`as-of ${$('asOfDate').value||'--'}`;$('safeKpi').innerHTML=safe===null?'--':`${fmt(safe)}<span class="unit">万円</span>`;$('safeYearsHint').textContent=e.livingExit&&safe!==null?`Exit年生活費の ${(safe/e.livingExit).toFixed(1)}年分`:'退職防衛用に指定した金額';$('reExitKpi').innerHTML=`${fmt(rt.exit)}<span class="unit">万円/年</span>`;$('reConfidenceHint').textContent=`物件CF weighted confidence ${Math.round(d.reQ)}%`;$('projectionKpi').innerHTML=`${fmt(p.base.end)}<span class="unit">万円</span>`;$('projectionMarginHint').textContent=d.margin===null?'必要資本との差 --':`必要資本比 ${d.margin>=0?'+':''}${d.margin.toFixed(1)}%`;
 $('score').textContent=d.score+'%';$('ring').style.background=`conic-gradient(var(--blue) ${d.score*3.6}deg,#253750 0deg)`;$('scoreBar').style.width=d.score+'%';$('verdict').textContent=d.verdict;$('verdict').className=d.verdict==='GO'?'good':d.verdict==='BUILD'?'bad':'warn';$('vtext').textContent=d.text;$('status').textContent=$('mode').value==='personal'?'PERSONAL EXIT':'FULL FIRE';$('dqPct').textContent=Math.round(dq.score)+'%';$('capitalMargin').textContent=d.margin===null?'--':`${d.margin>=0?'+':''}${d.margin.toFixed(1)}%`;$('safeYears').textContent=e.livingExit&&safe!==null?(safe/e.livingExit).toFixed(1)+'年':'--';$('scoreNote').textContent=`Base ${fmt(p.base.end)}万円 ｜ Target ${d.target===null?'--':fmt(d.target)+'万円'} ｜ DQ ${Math.round(dq.score)}%`;
 $('gateGrid').innerHTML=d.gates.map(g=>{const cls=g.pass===true?'tag-pass':g.pass===null?'tag-pending':'tag-fail',txt=g.pass===true?'PASS':g.pass===null?'PENDING':'FAIL';return `<div class="gate ${g.critical?'critical':''}"><div class="ghead"><b>${g.name}</b><span class="${cls}">${txt} · ${g.w}pt</span></div><small>${g.desc}${g.critical?' / Critical':''}</small></div>`}).join('');$('criticalCount').textContent=`Critical ${d.gates.filter(g=>g.critical&&g.pass===true).length}/${d.gates.filter(g=>g.critical).length}`;$('blockers').innerHTML=d.blockers.length?`<b>Open blockers:</b> ${d.blockers.join(' / ')}`:'<b class="good">No open blockers.</b>';
 const sp=spendingStats();$('expenseCount').textContent=`${sp.count}/12`;$('expenseMean').textContent=sp.mean===null?'--':fmt(sp.mean)+'万円/月';$('expenseMedian').textContent=sp.median===null?'--':fmt(sp.median)+'万円/月';$('expenseAnnual').textContent=sp.annual===null?'--':fmt(sp.annual)+'万円/年';$('expenseCv').textContent=sp.cv===null?'--':sp.cv.toFixed(1)+'%';
 $('projCons').textContent=fmt(p.cons.end);$('projBase').textContent=fmt(p.base.end);$('projUp').textContent=fmt(p.up.end);renderProjectionChart(p);
 ['stressEq','stressDc','stressCash','stressGold'].forEach((id,i)=>$(id).textContent=fmt(sa.s[i])+'万');$('stressAssets').textContent=fmt(sa.total)+'万円';const av=assetValues(),risk=fa?((av[0]+av[1])/fa*100):0;$('riskShare').textContent=risk.toFixed(1)+'%';
 $('livingNowView').textContent=n('living')===null?'--':fmt(n('living'))+'万円/年';$('livingExitView').textContent=e.livingExit===null?'--':fmt(e.livingExit)+'万円/年';$('wifeExitView').textContent=fmt(e.wifeExit)+'万円/年';$('reExitView').textContent=fmt(e.re)+'万円/年';$('personalGap').textContent=e.personalGap===null?'--':fmt(e.personalGap)+'万円/年';$('personalTarget').textContent=e.personalTarget===null?'--':fmt(e.personalTarget)+'万円';$('fullGap').textContent=e.fullGap===null?'--':fmt(e.fullGap)+'万円/年';$('fullTarget').textContent=e.fullTarget===null?'--':fmt(e.fullTarget)+'万円';
 $('stressNeed').textContent=st.need===null?'--':fmt(st.need)+'万円';$('safeMargin').textContent=st.margin===null?'--':`${st.margin>=0?'+':''}${fmt(st.margin)}万円`;$('safeMargin').className=st.margin===null?'':st.margin>=0?'good':'bad';$('runway').textContent=st.runway===null?(st.annualNeed===0?'∞':'--'):st.runway.toFixed(1)+'年';$('stressNarrative').textContent=st.need===null?'生活費・移行バッファを入力するとStress必要現金を計算します。':`妻収入をゼロ、RE CFを${100-(n('reHaircut')||50)}%認識、修繕${fmt(n('repairShock')||0)}万円、移行費${fmt(n('transition')||0)}万円で評価。`;
 $('simMonthly').textContent=sim.missing?'--':`${sim.monthly>=0?'+':''}${fmt(sim.monthly)}万円/月`;$('simSafeEnd').textContent=sim.missing?'--':fmt(sim.endSafe)+'万円';$('simForcedSale').textContent=sim.missing?'--':fmt(sim.forced)+'万円';$('simPostShock').textContent=sim.missing?'--':fmt(sim.postShock)+'万円';$('simVerdict').textContent=sim.missing?'INPUT':sim.pass?'PASS':'FAIL';$('simVerdict').className=sim.missing?'warn':sim.pass?'good':'bad';$('simNarrative').textContent=sim.missing?'正常化生活費が必要です。':`本人給与=0。${sim.months}か月で安全資産が${fmt(sim.endSafe)}万円となり、${sim.pass?'強制売却不要':'不足分をポートフォリオから売却する必要あり'}。`;
 renderProperties();renderDQ(dq);
 $('decisionMemo').innerHTML=`<div class="memo-block"><b>Current call:</b> ${d.verdict} / ${d.score}点。Data Quality ${Math.round(dq.score)}%。</div><div class="memo-block"><b>2030 capital:</b> Base projection ${fmt(p.base.end)}万円 vs selected target ${d.target===null?'--':fmt(d.target)+'万円'}${d.margin===null?'':`（margin ${d.margin>=0?'+':''}${d.margin.toFixed(1)}%）`}。</div><div class="memo-block"><b>Liquidity:</b> ${st.margin===null?'未確定':st.margin>=0?`Stress必要現金を${fmt(st.margin)}万円上回る`:`Stress必要現金に${fmt(Math.abs(st.margin))}万円不足`}。</div><div class="memo-block"><b>Primary blockers:</b> ${d.blockers.length?d.blockers.join(' / '):'なし'}。</div>`;
 localSave();
}
function renderMonths(){const root=$('expenseMonths');root.innerHTML=monthLabels.map((m,i)=>`<div class="month"><label>${m}</label><input class="expense-month" data-i="${i}" type="number" min="0" step="1" placeholder="万円"></div>`).join('')}
function state(){return{version:stateVersion,savedAt:new Date().toISOString(),mode:$('mode').value,exitDate:$('exitDate').value,asOfDate:$('asOfDate').value,living:$('living').value,safe:$('safe').value,transition:$('transition').value,contrib:$('contrib').value,wife:$('wife').value,wifeGrowth:$('wifeGrowth').value,inflation:$('inflation').value,swr:$('swr').value,policyFloor:$('policyFloor').value,capitalMarginPolicy:$('capitalMarginPolicy').value,safeYearsTarget:$('safeYearsTarget').value,reHaircut:$('reHaircut').value,repairShock:$('repairShock').value,riskCons:$('riskCons').value,riskBase:$('riskBase').value,riskUp:$('riskUp').value,goldReturn:$('goldReturn').value,expenseOk:$('expenseOk').checked,bsOk:$('bsOk').checked,contribOk:$('contribOk').checked,systemOk:$('systemOk').checked,pseudoDone:$('pseudoDone').checked,assets:$$('.asset').map(x=>x.value),hair:$$('.hair').map(x=>x.value),expenseMonths:$$('.expense-month').map(x=>x.value),properties,sim:{months:$('simMonths').value,wifePct:$('simWifePct').value,rePct:$('simRePct').value,marketShock:$('simMarketShock').value,repair:$('simRepair').value,useExitRe:$('simUseExitRe').checked,transition:$('simTransition').checked}}}
function migrateState(s){if(!s)return null;if(s.version>=4)return s;const m={...s,version:4,asOfDate:s.asOfDate||'2026-08-10',wifeGrowth:s.wifeGrowth??0,inflation:s.inflation??2,policyFloor:s.policyFloor??12000,capitalMarginPolicy:s.capitalMarginPolicy??10,safeYearsTarget:s.safeYearsTarget??2,reHaircut:s.reHaircut??50,repairShock:s.repairShock??200,riskCons:s.riskCons??0,riskBase:s.riskBase??3,riskUp:s.riskUp??5,goldReturn:s.goldReturn??1,contribOk:s.contribOk??false,pseudoDone:s.pseudoDone??false,expenseMonths:s.expenseMonths||Array(12).fill('')};if(!m.properties){m.properties=defaultProperties();const rn=s.rn||s.reNow||[],rx=s.rx||s.reExit||[];m.properties.forEach((p,i)=>{if(rn[i]!==undefined&&rn[i]!=='')p.overrideNow=vnum(rn[i]);if(rx[i]!==undefined&&rx[i]!=='')p.overrideExit=vnum(rx[i])})}return m;}
function apply(s){s=migrateState(s);if(!s)return;const ids=['mode','exitDate','asOfDate','living','safe','transition','contrib','wife','wifeGrowth','inflation','swr','policyFloor','capitalMarginPolicy','safeYearsTarget','reHaircut','repairShock','riskCons','riskBase','riskUp','goldReturn'];ids.forEach(k=>{if(s[k]!==undefined&&s[k]!==null&&s[k]!=='')$(k).value=s[k]});['expenseOk','bsOk','contribOk','systemOk','pseudoDone'].forEach(k=>{if(s[k]!==undefined)$(k).checked=!!s[k]});if(Array.isArray(s.assets))$$('.asset').forEach((x,i)=>{if(s.assets[i]!==undefined)x.value=s.assets[i]});if(Array.isArray(s.hair))$$('.hair').forEach((x,i)=>{if(s.hair[i]!==undefined)x.value=s.hair[i]});if(Array.isArray(s.expenseMonths))$$('.expense-month').forEach((x,i)=>{if(s.expenseMonths[i]!==undefined)x.value=s.expenseMonths[i]});if(Array.isArray(s.properties))properties=s.properties.map(p=>({...p}));if(s.sim){$('simMonths').value=s.sim.months??6;$('simWifePct').value=s.sim.wifePct??100;$('simRePct').value=s.sim.rePct??100;$('simMarketShock').value=s.sim.marketShock??0;$('simRepair').value=s.sim.repair??0;$('simUseExitRe').checked=!!s.sim.useExitRe;$('simTransition').checked=!!s.sim.transition}dirty=false;update();setDirty(false);}
function localSave(){try{localStorage.setItem('retirementLocalV4',JSON.stringify(state()))}catch(e){}}
function localLoad(){try{const s=JSON.parse(localStorage.getItem('retirementLocalV4')||localStorage.getItem('retirementLocal')||'null');if(s)apply(s)}catch(e){}}
function markDirty(){dirty=true;setDirty(true)}function setDirty(x){dirty=x;$('dirty').textContent=x?'未保存変更あり':'クラウド保存済';$('dirty').className=x?'pill warnpill':'pill';}
function openModal(id){$(id).style.display='grid'}function closeModal(id){$(id).style.display='none'}
function bind(){$$('input,select').forEach(x=>{x.addEventListener('input',()=>{markDirty();update()});x.addEventListener('change',()=>{markDirty();update()})});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}})}
const sb=(window.SUPABASE_CONFIG?.url&&!window.SUPABASE_CONFIG.url.includes('YOUR_'))?supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.publishableKey):null;
let cloudUser=null;
async function signup(){if(!sb){$('amsg').textContent='Supabase設定がありません。';return}const{error}=await sb.auth.signUp({email:$('email').value.trim(),password:$('pw').value,options:{emailRedirectTo:location.href}});$('amsg').textContent=error?error.message:'登録しました。確認メールが届いた場合はリンクを開いてください。'}
async function login(){if(!sb){$('amsg').textContent='Supabase設定がありません。';return}const{error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('pw').value});$('amsg').textContent=error?error.message:'ログインしました。'}
async function logout(){if(sb)await sb.auth.signOut()}
async function getCloudUser(){const{data,error}=await sb.auth.getUser();if(error)throw error;cloudUser=data.user;return cloudUser}
async function initCloud(){if(!sb){$('amsg').textContent='Supabase接続設定が未設定です。';return}const{data:{session}}=await sb.auth.getSession();if(session?.user){cloudUser=session.user;await afterLogin()}sb.auth.onAuthStateChange(async(_,session)=>{cloudUser=session?.user||null;if(cloudUser)await afterLogin();else{$('auth').style.display='grid';$('cloudUser').textContent='未ログイン';$('cloud').textContent='Cloud: 未接続'}})}
async function afterLogin(){$('auth').style.display='none';$('cloudUser').textContent=cloudUser.email||'ログイン済';$('cloud').textContent='Cloud: 接続済';await cloudLoad(true)}
function quarterRecord(){const d=new Date(),q=`${d.getFullYear()}-Q${Math.floor(d.getMonth()/3)+1}`,dec=lastDecision.e?lastDecision:decision();return{q,d:d.toISOString().slice(0,10),fa:Math.round(financialAssets()),safe:Math.round(n('safe')||0),re:Math.round(reTotals().exit),living:Math.round(n('living')||0),score:dec.score,dq:Math.round(dec.dq.score),proj:Math.round(dec.p.base.end),verdict:dec.verdict}}
async function cloudSave(addQuarter=false){if(!sb||!cloudUser){alert('先にログインしてください。');return}$('cloud').textContent='Cloud: 保存中…';try{const u=await getCloudUser();let hist=Array.isArray(u.user_metadata?.hist)?[...u.user_metadata.hist]:[];if(addQuarter){const r=quarterRecord();hist=hist.filter(x=>x.q!==r.q);hist.push(r);hist=hist.sort((a,b)=>a.q.localeCompare(b.q)).slice(-20)}const{error}=await sb.auth.updateUser({data:{retirement_state:state(),hist}});if(error)throw error;$('cloud').textContent=`Cloud保存: ${new Date().toLocaleString('ja-JP')}${addQuarter?' / 四半期更新':''}`;setDirty(false)}catch(e){$('cloud').textContent='Cloud保存エラー';alert(e.message||String(e))}}
async function cloudLoad(silent=false){if(!sb||!cloudUser)return;$('cloud').textContent='Cloud: 読込中…';try{const u=await getCloudUser(),s=u.user_metadata?.retirement_state;if(s){apply(s);$('cloud').textContent=`Cloud読込済: ${cloudUser.email}`;setDirty(false)}else{$('cloud').textContent='Cloud: 初回保存待ち';if(!silent)alert('クラウド保存データはまだありません。')}}catch(e){$('cloud').textContent='Cloud読込エラー';if(!silent)alert(e.message||String(e))}}
async function showHistory(){if(!sb||!cloudUser)return;try{const u=await getCloudUser(),h=Array.isArray(u.user_metadata?.hist)?u.user_metadata.hist:[];drawHistoryChart('histFa',h,'fa');drawHistoryChart('histSafe',h,'safe');drawHistoryChart('histRe',h,'re');drawHistoryChart('histScore',h,'score','%');$('histBody').innerHTML=h.length?[...h].reverse().map(r=>`<tr><td>${r.q}</td><td>${fmt(vnum(r.fa))}</td><td>${vnum(r.safe)===null?'--':fmt(vnum(r.safe))}</td><td>${fmt(vnum(r.re))}</td><td>${vnum(r.living)===null?'--':fmt(vnum(r.living))}</td><td>${fmt(vnum(r.score))}%</td><td>${vnum(r.dq)===null?'--':fmt(vnum(r.dq))+'%'}</td><td>${r.verdict||'--'}</td></tr>`).join(''):'<tr><td colspan="8" class="muted">履歴はまだありません。「四半期記録」で現在Quarterを保存してください。</td></tr>';openModal('historyModal')}catch(e){alert(e.message||String(e))}}
renderMonths();renderRoadmap();localLoad();bind();update();initCloud();
